---
apiVersion: v1
kind: Service
metadata:
  name: social-graph-mongodb
  labels:
    death-star-project: social-network
    app: social-graph-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app: social-graph-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-mongodb
  labels:
    death-star-project: social-network
    app: social-graph-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: social-graph-mongodb
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app: social-graph-mongodb
      name: social-graph-mongodb
    spec:
      containers:
      - name: social-graph-mongodb
        image: stvdputten/mongo
        volumeMounts:
          - name: my-data
            mountPath: "/data/db"
        resources:  
          limits:
            cpu: "2"
            memory: 2GiB
      restartPolicy: Always
      volumes:
      - name: my-data
        emptyDir: {}
