---
apiVersion: v1
kind: Service
metadata:
  name: review-storage-memcached
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app: review-storage-memcached
spec:
  ports:
  - port: 11211
  selector:
    death-star-project: media-microsvc
    app: review-storage-memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-storage-memcached
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app: review-storage-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: media-microsvc
      app: review-storage-memcached
  template:
    metadata:
      labels: 
        death-star-project: media-microsvc
        app: review-storage-memcached
      name: review-storage-memcached
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: review-storage-memcached
        resources:
          limits:
            cpu: "2.0"
            memory: "2GiB"
        image: memcached:1.6.9
      restartPolicy: Always
