apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-rate
  name: mongodb-rate
spec:
  ports:
    - name: "27020"
      port: 27020
      targetPort: 27017
  selector:
    io.kompose.service: mongodb-rate
status:
  loadBalancer: {}
