apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
    kompose.version: 1.26.0 (HEAD)
  labels:
    io.kompose.service: mongodb-geo
  name: mongodb-geo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-geo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
        kompose.version: 1.26.0 (HEAD)
      labels:
        io.kompose.service: mongodb-geo
    spec:
      containers:
        - image: stvdputten/mongo
          name: mongodb-geo
          ports:
          - containerPort: 27017
          resources:
            limits:
              cpu: "2.0"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /data/db
              name: geo
      restartPolicy: Always
      volumes:
        - name: geo
          persistentVolumeClaim:
            claimName: geo
status: {}
