apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: user
  name: user
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  storageClassName: user-storage
status: {}
