apiVersion: v1
kind: PersistentVolume
metadata:
  name: reservation-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: reservation-storage
  hostPath:
    path: /proj/sched-serv-PG0/exp/stvdp-111011/tmp/reservation   # Where all the hard drives are mounted
    type: Directory