apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
    kompose.version: 1.26.0 (HEAD)
  labels:
    io.kompose.service: geo
  name: geo
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: geo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
        kompose.version: 1.26.0 (HEAD)
      labels:
        io.kompose.service: geo
    spec:
      containers:
        - command:
            - geo
          image: stvdputten/hotel_reserv_geo_single_node:kubernetes
          name: geo
          ports:
            - containerPort: 8083
          resources:
            limits:
              cpu: "1.0"
              memory: "1Gi"
          volumeMounts:
          - mountPath: /go/src/github.com/harlow/go-micro-services/config.json
            subPath: config.json
            name: config-json
      restartPolicy: Always
      volumes :
      - name: config-json
        configMap:
          name: configmap-config-json
          items:
          - key: config.json
            path: config.json
status: {}