apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
    kompose.version: 1.26.0 (HEAD)
  labels:
    io.kompose.service: mongodb-recommendation
  name: mongodb-recommendation
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: mongodb-recommendation
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
        kompose.version: 1.26.0 (HEAD)
      labels:
        io.kompose.service: mongodb-recommendation
    spec:
      containers:
        - image: stvdputten/mongo
          name: mongodb-recommendation
          ports:
            - containerPort: 27017
          resources: 
            limits:
              cpu: "1.0"
              memory: "1Gi"
      restartPolicy: Always
status: {}
