apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: rate
  name: rate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1GiB"
  storageClassName: rate-storage
status: {}
