apiVersion: v1
kind: PersistentVolume
metadata:
  name: rate-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "10GiB"
  storageClassName: rate-storage
  hostPath:
    path: /proj/sched-serv-PG0/exp/stvdp-111011/tmp/rate   # Where all the hard drives are mounted
    type: Directory