apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: recommendation
  name: recommendation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1GiB"
  storageClassName: recommendation-storage
status: {}
