---
apiVersion: v1
kind: Service
metadata:
  name: home-timeline-redis
  labels:
    death-star-project: social-network
    app: home-timeline-redis
  namespace: social-network
spec:
  ports:
  - port: 6379
  selector:
    death-star-project: social-network
    app: compose-post-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-timeline-redis
  labels:
    death-star-project: social-network
    app: home-timeline-redis
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: home-timeline-redis
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app: home-timeline-redis
      name: home-timeline-redis
    spec:
      containers:
      - name: home-timeline-redis
        image: redis:alpine3.13
        resources:
          limits:
            cpu: "1"
            memory: 0.2G
      restartPolicy: Always
