version: "3"
services:
  dns-media:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"
      placement:
        constraints:
          - node.role==worker
      restart_policy:
        condition: any
    image: defreitas/dns-proxy-server:2.19.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf

    unique-id-service:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4.0"
            memory: "1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: stvdputten/media-microservices:swarm
      hostname: unique-id-service
      entrypoint: UniqueIdService

    movie-id-service:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4.0"
            memory: "1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: stvdputten/media-microservices:swarm
      hostname: movie-id-service
      entrypoint: MovieIdService

    movie-id-mongodb:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: mongo:4.4.6
      hostname: movie-id-mongodb
      ports:
        - 27018:27017

    movie-id-memcached:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: memcached:1.6.9
      hostname: movie-id-memcached

    text-service:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4.0"
            memory: "1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: stvdputten/media-microservices:swarm
      hostname: text-service
      entrypoint: TextService

    rating-service:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4.0"
            memory: "1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: stvdputten/media-microservices:swarm
      hostname: rating-service
      entrypoint: RatingService

    rating-redis:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4.0"
            memory: "1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: redis:alpine3.13
      hostname: rating-redis

    user-service:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4.0"
            memory: "1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: stvdputten/media-microservices:swarm
      hostname: user-service
      entrypoint: UserService

    user-mongodb:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: mongo:4.4.6
      hostname: user-mongodb
      ports:
        - 27019:27017

    user-memcached:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: memcached:1.6.9
      hostname: user-memcached

    compose-review-service:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "12.0"
            memory: "1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: stvdputten/media-microservices:swarm
      hostname: compose-review-service
      entrypoint: ComposeReviewService

    compose-review-memcached:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "3.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: memcached:1.6.9
      hostname: compose-review-memcached

    review-storage-service:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: stvdputten/media-microservices:swarm
      hostname: review-storage-service
    entrypoint: ReviewStorageService

    review-storage-mongodb:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.3G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: mongo:4.4.6
      hostname: review-storage-mongodb
      ports:
        - 27020:27017

    review-storage-memcached:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: memcached:1.6.9
      hostname: review-storage-memcached

    user-review-service:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4.0"
            memory: "1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: stvdputten/media-microservices:swarm
      hostname: user-review-service
      entrypoint: UserReviewService

    user-review-mongodb:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4.0"
            memory: "0.3G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: mongo:4.4.6
      hostname: user-review-mongodb
      ports:
        - 27021:27017

    user-review-redis:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: redis:alpine3.13
      hostname: user-review-redis

    movie-review-service:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4.0"
            memory: "1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: stvdputten/media-microservices:swarm
      hostname: movie-review-service
      entrypoint: MovieReviewService

    movie-review-mongodb:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4.0"
            memory: "0.3G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: mongo:4.4.6
      hostname: movie-review-mongodb
      ports:
        - 27022:27017

    movie-review-redis:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: redis:alpine3.13
      hostname: movie-review-redis

    nginx-web-server:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4.0"
            memory: "4G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: yg397/openresty-thrift:xenial
      hostname: nginx-thrift
      ports:
        - 8080:8080
      volumes:
        - ./nginx-web-server/lua-scripts:/usr/local/openresty/nginx/lua-scripts
        - ./nginx-web-server/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
        - ./nginx-web-server/jaeger-config.json:/usr/local/openresty/nginx/jaeger-config.json
        - ./gen-lua:/gen-lua

    cast-info-service:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "4.0"
            memory: "1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: stvdputten/media-microservices:swarm
      hostname: cast-info-service
      entrypoint: CastInfoService

    cast-info-mongodb:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.2G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: mongo:4.4.6
      hostname: cast-info-mongodb
      ports:
        - 27024:27017

    cast-info-memcached:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: memcached:1.6.9
      hostname: cast-info-memcached

    plot-service:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: stvdputten/media-microservices:swarm
      hostname: plot-service
      entrypoint: PlotService

    plot-mongodb:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: mongo:4.4.6
      hostname: plot-mongodb
      ports:
        - 27025:27017

    plot-memcached:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: memcached:1.6.9
      hostname: plot-memcached

    movie-info-service:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: stvdputten/media-microservices:swarm
      hostname: movie-info-service
      entrypoint: MovieInfoService

    movie-info-mongodb:
      deploy:
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        replicas: 1
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: mongo:4.4.6
      hostname: movie-info-mongodb
      ports:
        - 27026:27017

    movie-info-memcached:
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1.0"
            memory: "0.1G"
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: memcached:1.6.9
      hostname: movie-info-memcached

    jaeger:
      deploy:
        replicas: 1
        placement:
          constraints:
            - node.role==worker
        restart_policy:
          condition: any
      image: jaegertracing/all-in-one:latest
      hostname: jaeger
      ports:
        - 16686:16686
    environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411