apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: profile
  name: profile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  storageClassName: profile-storage
status: {}
