---
apiVersion: v1
kind: Service
metadata:
  name: text-service
  labels:
    death-star-project: social-network
    app: text-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: text-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-service
  labels:
    death-star-project: social-network
    app: text-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: text-service
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app: text-service
      name: text-service
    spec:
      containers:
      - name: text-service
        # image: stvdputten/social-network-microservices:kubernetes
        image: poanpan/social-network-microservices-local-jaeger:v0.0.1
        command: ["TextService"]
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
        resources:  
          limits:
            cpu: "1.0"
            memory: 1GiB
      restartPolicy: Always
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
