#     depends_on:
      # - write-home-timeline-rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: write-home-timeline-service
  labels:
    death-star-project: social-network
    app: write-home-timeline-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: write-home-timeline-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-home-timeline-service
  labels:
    death-star-project: social-network
    app: write-home-timeline-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: write-home-timeline-service
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app: write-home-timeline-service
      name: write-home-timeline-service
    spec:
      containers:
      - name: write-home-timeline-service
        resources:  
          limits:
            cpu: "1"
            memory: 1GiB
        # image: poanpan/rabbitmq:v1
        image: poanpan/social-network-microservices-local-jaeger:v0.0.1
        command: ["WriteHomeTimelineService"]
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
      initContainers:
        - name: wait-write-home-timeline-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup write-home-timeline-rabbitmq.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
      restartPolicy: Always
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
