---
apiVersion: v1
kind: Service
metadata:
  name: home-timeline-service
  labels:
    death-star-project: social-network
    app: home-timeline-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: home-timeline-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-timeline-service
  labels:
    death-star-project: social-network
    app: home-timeline-service
  namespace: social-network
spec:
  replicas: 2
  selector:
    matchLabels:
      death-star-project: social-network
      app: home-timeline-service
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app: home-timeline-service
      name: home-timeline-service
    spec:
      containers:
      - name: home-timeline-service
        # image: stvdputten/social-network-microservices:kubernetes
        image: poanpan/social-network-microservices-local-jaeger:v0.0.1
        command: ["HomeTimelineService"]
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
        resources:
          limits:
            cpu: "1"
            memory: 1GiB
      restartPolicy: Always
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
