---
apiVersion: v1
kind: Service
metadata:
  name: post-storage-service
  labels:
    death-star-project: social-network
    app: post-storage-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: post-storage-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-storage-service
  labels:
    death-star-project: social-network
    app: post-storage-service
  namespace: social-network
spec:
  replicas: 2
  selector:
    matchLabels:
      death-star-project: social-network
      app: post-storage-service
  template:
    metadata:
      labels: 
        death-star-project: social-network
        app: post-storage-service
      name: post-storage-service
    spec:
      containers:
      - name: post-storage-service
        # image: stvdputten/social-network-microservices:kubernetes
        image: poanpan/social-network-microservices-local-jaeger:v0.0.1
        command: ["PostStorageService"]
        imagePullPolicy: Always
        ports: 
        - containerPort: 9090
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
        resources:  
          limits:
            cpu: "1"
            memory: "1Gi"
      restartPolicy: Always
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
