apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: geo
  name: geo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: geo-storage
  selector:
    matchLabels:
      io.kompose.service: geo
  resources:
    requests:
      storage: 100Mi
status: {}
