apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-geo
  name: mongodb-geo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-geo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-geo
    spec:
      containers:
        - image: mongo:4.4.6
          name: mongodb-geo
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
