apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: reservation
  name: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reservation
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: reservation
    spec:
      containers:
        - command:
            - reservation
          image: stvdputten/hotel_reserv_reserve_single_node:kubernetes
          name: reservation
          ports:
            - containerPort: 8087
          resources: {}
      restartPolicy: Always
status: {}
