apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: search
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: search
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: search
    spec:
      containers:
        - command:
            - search
          image: stvdputten/hotel_reserv_search_single_node:kubernetes
          name: search
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
