apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
    kompose.version: 1.26.0 (HEAD)
  labels:
    io.kompose.service: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-swarm-local.yml
        kompose.version: 1.26.0 (HEAD)
      labels:
        io.kompose.service: user
    spec:
      containers:
        - command:
            - user
          image: stvdputten/hotel_reserv_user_single_node:kubernetes
          name: user
          ports:
            - containerPort: 8086
          resources: 
            limits:
              cpu: "4"
              memory: "1Gi"
          volumeMounts:
          - mountPath: /go/src/github.com/harlow/go-micro-services/config.json
            subPath: config.json
            name: config-json
      restartPolicy: Always
      volumes :
      - name: config-json
        configMap:
          name: configmap-config-json
          items:
          - key: config.json
            path: config.json
status: {}
